### ISSUE TITLE
How we should build web layout?

### ISSUE THREAD

**Issue by Szymiks** [Code-Poets/sheetstorm#101]
I am learning html now and I find that websites should be builded with `divs`. However, our `base.html` is builded on `tables`. I would like to ask you what do you think about this? Is it a good way to create our web app?l
[Topic about using divs and tables](https://www.webmasterworld.com/html/4628956.htm)

**Comment by Karrp** [comment]
@maciejSamerdak you can know something on this topic.

**Comment by maciejSamerdak** [comment]
From what I've seen myself on HTML tutorials, I can confirm that usage of divs over tables is absolutely encouraged. It is considered the best, most responsive way to design a web app, so I see no reason why we shouldn't apply this to our own.

Although, to make it clear, I believe *_<table>_* tags should still be used with actual table elements (like table containing report's list), since *_<div>_* relates more to layout organisation, as far as I know.
Am I correct?
