### ISSUE TITLE
URL to editing profile contain user ID

### ISSUE THREAD

**Issue by kbeker** [Code-Poets/sheetstorm#182]
Currently during editing profile we can change edited profile to any other which already is created in database. ID should be handled from request body instead of URL.

Current state:
```
http://sheetstorm.codepoets.it/user/profile/1
```
Recommended state:
```
http://sheetstorm.codepoets.it/user/profile
```

**Comment by rwrzesien** [comment]
Similar question to this in https://github.com/Code-Poets/sheetstorm/issues/183#issuecomment-493799627 - who exactly should be able to edit users? If only user himself, we can avoid having ID in url and get it from `request`. Otherwise (if manager or admin can edit too) we have to pass it somehow, so then it should stay.

**Comment by Karrp** [comment]
Also admin should be able to edit users.

**Comment by rwrzesien** [comment]
> Also admin should be able to edit users.

For this we have two separate views, so we can remove `id` from the one when user is editing his own profile, and for the admin editing user we can't before of reasons explained here: https://github.com/Code-Poets/sheetstorm/issues/183#issuecomment-494478393. But if while working on this I will find out that those two views can be easily combined and access can be secured on the view level, I would still insist on keeping the ID in the combined url/view.

**Comment by Karrp** [comment]
OK
Do what you think it should be good.
