### ISSUE TITLE
Feature distribution of reports for months

### ISSUE THREAD

**Issue by Karrp** [Code-Poets/sheetstorm#25]
On one view of reports should be just one month at the same time

- [x] User's reports
- [x] Reports per project
- [x] Reports per author

**Comment by rwrzesien** [comment]
@maciejSamerdak What is the status of this? Was the last checkpoint resolved, or is in one of pending pull requests?

**Comment by maciejSamerdak** [comment]
@rwrzesien The last checkpoint is not currently in development at all, since the last view was of lower priority. However, since it has been already introduced to the master, this feature should be applied to it as well. The remaining two are in pending pull requests:
https://github.com/Code-Poets/sheetstorm/pull/138
https://github.com/Code-Poets/sheetstorm/pull/139
