### ISSUE TITLE
Invisible numbers in the exported reports xlsx file preview in the Gmail.

### ISSUE THREAD

**Issue by Karrp** [Code-Poets/sheetstorm#531]
The error probably lies with Google, but we may be able to work around it somehow.

![image](https://user-images.githubusercontent.com/37847362/64171673-7dd18000-ce53-11e9-9105-d59f693c8249.png)

**Comment by Szymiks** [comment]
I have checked the problem and it seems to be problem with cell format for total hours because as we would like to sum all hours this cell has code format [H]:MM and it makes that all cells in column don't show hours. After changing it to normal duration format it works but doesn't show total hours as we want but `00:00`

**Comment by Karrp** [comment]
I reported it to google, but I think we will have to fix it somehow on our own anyway. :(
